spring:
  datasource:
    url: jdbc:mysql://159.75.156.115:13306/motion?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: xiaoli
    password: abC123456@
    driver-class-name: com.mysql.cj.jdbc.Driver
