spring:
  datasource:
    url: jdbc:mysql://159.75.156.115:3306/motion?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: xiaoli
    password: abC123456@
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 114.132.67.226
    port: 6379
    password: abC123456@
    database: 2


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB



server:
  port: 8060
  tomcat:
    uri-encoding: UTF-8
quin:
  accessKey: "MAh90OZvgbaAY6m5g8DhtNC5s7TtFomeGHu2pCrT"
  secretKey: "Zm2fQUO3zMIH7R8psNby8oCqywT8QshxcXjNc54A"
  bucket: "motion1024"
  domain: "http://s36fh9xu3.hn-bkt.clouddn.com"
